import { Inter } from "next/font/google";
import "./globals.css";
import { NextuiProviderWrapper } from "./providers";
import { Providers } from "../lib/providers";
import Nav from "@/components/Navbarcomponets/Nav";
import Sidenav from "@/components/Navbarcomponets/Sidenav";
import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
    <html lang="en">
      <body className={inter.className}>
        <NextuiProviderWrapper>
          {/* <main className="grid grid-cols-1 md:grid-cols-[auto,1fr] bg-[#f7f7f7]  w-full">
            <div className="w-full  h-full">
              <Sidenav />
            </div>

            <section className="flex  flex-col gap-4 w-full h-full ">
              <Nav /> */}
              {children}
            {/* </section>
          </main> */}
          <Toaster/>
        </NextuiProviderWrapper>
      </body>
    </html>

    </Providers>
  );
}
